<a href="https://colab.research.google.com/github/saiavinash77/Maths_for_ML/blob/main/3_Working_with_Matrix.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## ***In this part we are gonna working with How to create a Matrix and some manipulations with them ***

IMporting The Dependencies

In [1]:
import numpy as np

Creating a Matrix Using Numpy

In [3]:
matrix_1 = np.array([[1,2],[3,4]])

In [5]:
print(matrix_1)

[[1 2]
 [3 4]]


Knowing The Length Of the Matrix ,i mean How many rows and columns (r,c)

In [6]:
matrix_2 = np.array([[10,30,40],[20,40,60],[20,15,19]])

In [7]:
print(matrix_2)

[[10 30 40]
 [20 40 60]
 [20 15 19]]


In [8]:
matrix_2.shape

(3, 3)

Creating a matrix with random Values

In [9]:
# importing the dependencies

import random

In [10]:
random_array = np.random.rand(2,3)

print(random_array)

[[0.10654823 0.43210642 0.89060474]
 [0.27821193 0.8150686  0.77801136]]


In [17]:
# creating a matrix with random numbers upto 100
random_integer_matrix = np.random.randint(100,size = (4,5))
print(random_integer_matrix)

[[ 0 11 91  8 88]
 [82 66 99 20 93]
 [52 15 63 29 23]
 [38 62 56 29 98]]


In [28]:
#  creating a matrix with all ones with float values

matrix_3 = np.ones((2,3))
print(matrix_3)

[[1. 1. 1.]
 [1. 1. 1.]]


In [27]:
# creating a matrix with all ones

matrix_3 = np.ones((10,10),dtype = int)
print(matrix_3)

[[1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]]


In [33]:
# creating all the matrix with zeroes

Zero_mat = np.zeros((4,5))
print(Zero_mat)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [34]:
# creating all the matrix with zeroes

Zero_mat = np.zeros((4,5),dtype = int)
print(Zero_mat)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


Identity Matrix

In [36]:
identity = np.eye(3,3)
identity

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [38]:
# Matrix With random integer Values Doing Transpose for this
# This is a normal One
Matrix_conversion = np.random.randint(100,size = (5,5))
print(Matrix_conversion)

[[ 7 97 62 53 49]
 [62 38 85 34 76]
 [ 4  3 55 36 63]
 [51 54 80 50 73]
 [60 44 81 62 47]]


In [39]:
# Herre is the Transposed one

transpose = np.transpose(Matrix_conversion)

In [40]:
transpose

array([[ 7, 62,  4, 51, 60],
       [97, 38,  3, 54, 44],
       [62, 85, 55, 80, 81],
       [53, 34, 36, 50, 62],
       [49, 76, 63, 73, 47]])