<a href="https://colab.research.google.com/github/saiavinash77/Maths_for_ML/blob/main/4_Matrix_Operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
# Matrix_addition
import numpy as np
matrix_1 = np.array([[2,3],[10,5]])
matrix_2 = np.array([[10,5],[20,4]])

In [7]:
# This is all about matrix addition

print(matrix_1+matrix_2)

[[12  8]
 [30  9]]


In [10]:
# Matrix Subtraction

matrix_3 = np.array([[2,3],[10,5]])
matrix_4 = np.array([[10,5],[20,4]])
print(matrix_3-matrix_4)

[[ -8  -2]
 [-10   1]]


In [11]:
# Multiplying a matrix by a sclar

scalar = 4

matrix_5 = np.array([[2,4,6]])
print(scalar * matrix_5)

[[ 8 16 24]]


In [12]:
# Note : Vectors are the matrix with either 1 row or 1 column

In [13]:
# ThankYou For Checking🥳🥳🥳🥳🥳🥳